### ISSUE TITLE
Move to new travis infrastructure

### ISSUE THREAD

**Issue by dhensby** [silverstripe-labs/silverstripe-textextraction#16]
Need to stop using sudo and add `sudo: false` to the `.travis.yml` file

**Comment by tractorcow** [comment]
Then make a PR. :D

**Comment by dhensby** [comment]
see https://github.com/travis-ci/apt-package-whitelist/pull/22

**Comment by tractorcow** [comment]
oh lol. :D

**Comment by tractorcow** [comment]
I've created https://github.com/travis-ci/travis-ci/issues/4516 since this seems to be the standard mechanism for requesting new packages.

**Comment by tractorcow** [comment]
xpdf is added :D

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe-labs/silverstripe-textextraction/pull/17
